icons.card = {
	health:'./Assets/icons/card/health.svg',
	armor:'./Assets/icons/card/armor.svg',
	character: {
		"Blood Knight": './Assets/icons/card/character/Blood_Knight.svg',
		"Blood Guard": './Assets/icons/card/character/Blood_Guard.svg',
		"Blood Thief": './Assets/icons/card/character/Blood_Thief.svg',
		"Blood Monk": './Assets/icons/card/character/Blood_Monk.svg',
		"Blood Ranger": './Assets/icons/card/character/Blood_Ranger.svg',
		"Blood Barbarian": './Assets/icons/card/character/Blood_Barbarian.svg',
		"Blood Troll": './Assets/icons/card/character/Blood_Troll.svg',
		"Armored Knight": './Assets/icons/card/character/Armored_Knight.svg',
		"Armored Guard": './Assets/icons/card/character/Armored_Guard.svg',
		"Armored Thief": './Assets/icons/card/character/Armored_Thief.svg',
		"Armored Monk": './Assets/icons/card/character/Armored_Monk.svg',
		"Armored Ranger": './Assets/icons/card/character/Armored_Ranger.svg',
		"Armored Barbarian": './Assets/icons/card/character/Armored_Barbarian.svg',
		"Armored Troll": './Assets/icons/card/character/Armored_Troll.svg',
		"Fairy Knight": './Assets/icons/card/character/Fairy_Knight.svg',
		"Fairy Guard": './Assets/icons/card/character/Fairy_Guard.svg',
		"Fairy Thief": './Assets/icons/card/character/Fairy_Thief.svg',
		"Fairy Monk": './Assets/icons/card/character/Fairy_Monk.svg',
		"Fairy Ranger": './Assets/icons/card/character/Fairy_Ranger.svg',
		"Fairy Barbarian": './Assets/icons/card/character/Fairy_Barbarian.svg',
		"Fairy Troll": './Assets/icons/card/character/Fairy_Troll.svg',
		"Dark Knight": './Assets/icons/card/character/Dark_Knight.svg',
		"Dark Guard": './Assets/icons/card/character/Dark_Guard.svg',
		"Dark Thief": './Assets/icons/card/character/Dark_Thief.svg',
		"Dark Monk": './Assets/icons/card/character/Dark_Monk.svg',
		"Dark Ranger": './Assets/icons/card/character/Dark_Ranger.svg',
		"Dark Barbarian": './Assets/icons/card/character/Dark_Barbarian.svg',
		"Dark Troll": './Assets/icons/card/character/Dark_Troll.svg',
		"Adventuring Knight": './Assets/icons/card/character/Adventuring_Knight.svg',
		"Adventuring Guard": './Assets/icons/card/character/Adventuring_Guard.svg',
		"Adventuring Thief": './Assets/icons/card/character/Adventuring_Thief.svg',
		"Adventuring Monk": './Assets/icons/card/character/Adventuring_Monk.svg',
		"Adventuring Ranger": './Assets/icons/card/character/Adventuring_Ranger.svg',
		"Adventuring Barbarian": './Assets/icons/card/character/Adventuring_Barbarian.svg',
		"Adventuring Troll": './Assets/icons/card/character/Adventuring_Troll.svg'
	}
};